name: fyp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.16.0
  provider: ^6.0.2
  intl: ^0.17.0
  cloud_firestore: ^3.1.14
  shared_preferences: ^2.0.13
  json_annotation: ^4.5.0
  google_fonts: ^2.3.2
  uuid: ^3.0.6
  get_it: ^7.2.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  signature: ^5.0.0
  permission_handler: ^9.2.0
  path_provider: ^2.0.9
  firebase_storage: ^10.2.15
  flutter_easyloading: ^3.0.3
  crypt: ^4.2.1
  supercharged: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  introduction_screen: ^3.0.2
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  http: ^0.13.4
  pdf: ^3.8.1
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  json_serializable: ^6.2.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.jpg"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/native_splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
